[#9] [FEAT] 프로젝트 패키지 및 엔티티 맵핑
mash-up-kr/Backend_9th_Hoowook_Hoowook pull request #29
Opened 2020-05-25 09:16 UTC by jiss02

도메인 별 패키지를 생성하고 엔티티를 맵핑하였습니다.

resolve #9

2020-05-25 11:49 UTC, korea8378 commented on src/main/java/mashup/backend/hoowook_hoowwok/approval/domain/Approval.java
> +@NoArgsConstructor
현재 코드를 보면 Approval이라는 엔티티의 객체 생성 할수 있는 방법은 디폴트 생성자와 빌더패턴을 이용한 객체 생성 두가지가 있는데요. 빌더패턴을 사용하면 디폴트생성자로 객체 생성할 이유가 있을까요??

2020-05-25 11:49 UTC, korea8378 commented on src/main/java/mashup/backend/hoowook_hoowwok/approval/domain/Approval.java
> +    private User user;
ApprovalId라는 복합키를 사용하고 있는중인데 User라는 맵핑 관계가 필요할까요???

2020-05-25 11:49 UTC, korea8378 commented on src/main/java/mashup/backend/hoowook_hoowwok/approval/domain/Approval.java
> +    private Document document;
ApprovalId라는 복합키를 사용하고 있는중인데 Document라는 맵핑 관계가 필요할까요???(위와 동일한 이유입니다.)

2020-05-25 11:49 UTC, korea8378 commented on src/main/java/mashup/backend/hoowook_hoowwok/approval/domain/Approval.java
> +    private String state;
state라는 필드만 보고는 어떠한 상태들이 있는지 파악하기가 어려울꺼 같습니다. 좀 더 효율적으로 상태를 관리할수 있는 방법이 있지않을가요??

2020-05-25 11:49 UTC, korea8378 commented on src/main/java/mashup/backend/hoowook_hoowwok/approval/domain/ApprovalId.java
> +@Data
Lombok의 @data 어노테이션을 사용하면 getter, setter가 만들어지는데요. @Data보다는 정말로 필요한 어노테이션 추가해서 메서드를 제네레이션하는게 좋을것 같습니다.

2020-05-25 11:49 UTC, korea8378 commented on src/main/java/mashup/backend/hoowook_hoowwok/approval/controller/SignController.java
> +public class SignController {
도메인을 Approval로 가져가면 컨트롤러 네이밍을 Approval으로 맞쳐주는게 좋을것 같습니다.

2020-05-25 11:49 UTC, korea8378 commented on src/main/java/mashup/backend/hoowook_hoowwok/approval/service/SignService.java
> +public class SignService {
도메인을 Approval로 가져가면 서비스 네이밍을 Approval으로 맞쳐주는게 좋을것 같습니다.

2020-05-25 11:49 UTC, korea8378 commented on src/main/java/mashup/backend/hoowook_hoowwok/document/domain/Document.java
> +@NoArgsConstructor
현재 코드를 보면 Document이라는 엔티티의 객체 생성 할수 있는 방법은 디폴트 생성자와 빌더패턴을 이용한 객체 생성 두가지가 있는데요. 빌더패턴을 사용하면 디폴트생성자로 객체 생성할 이유가 있을까요??

2020-05-25 11:49 UTC, korea8378 commented on src/main/java/mashup/backend/hoowook_hoowwok/document/domain/Document.java
> +    private String state;
state라는 필드만 보고는 어떠한 상태들이 있는지 파악하기가 어려울꺼 같습니다. 좀 더 효율적으로 상태를 관리할수 있는 방법이 있지않을가요??

2020-05-25 11:49 UTC, korea8378 commented on src/main/java/mashup/backend/hoowook_hoowwok/document/domain/Document.java
> +    private User user;
문서 엔티티가 유저 엔티티를 직접 가지고 있을만큼 강한 의존성이 필요할까요??? 유저라는 도메인이 인증프로젝트를 위해 별도로 분리된다면 유저라는 엔티티(객체)를 참조할수있을까요??

2020-05-25 11:49 UTC, korea8378 commented on src/main/java/mashup/backend/hoowook_hoowwok/document/domain/Document.java
> +    public Document(User user, String content, String title, String state){
빌더패턴을 사용한다면 다른생성자는 private을 통하여 빌더패턴만 사용하게 해주는게 좋습니다.

2020-05-25 11:49 UTC, korea8378 commented on src/main/java/mashup/backend/hoowook_hoowwok/user/domain/RoleType.java
> +@RequiredArgsConstructor
enum은 보통 객체를 이미 생성하여 상수로 사용하기 위해 사용이됩니다. @RequiredArgsConstructor만 사용한다면 접근지정자가 기본적으로 public인데요. 그렇다면 다른 외부에서 RoleType이라는 객체를 생성할수 있지 않을까요?

2020-05-25 11:49 UTC, korea8378 commented on src/main/java/mashup/backend/hoowook_hoowwok/user/domain/User.java
> +    public User(RoleType roleType, String password, String name, String rank) {
빌더패턴을 사용한다면 다른생성자는 private을 통하여 빌더패턴만 사용하게 해주는게 좋습니다.

2020-05-25 12:35 UTC, jiss02 commented on src/main/java/mashup/backend/hoowook_hoowwok/approval/domain/Approval.java
> +@NoArgsConstructor
디폴트 생성자를를 붙이라는 오류 메세지가 계속 떠서 적은 어노테이션인데, 방법을 더 찾아보겠습니다.

2020-05-25 13:21 UTC, korea8378 commented on src/main/java/mashup/backend/hoowook_hoowwok/approval/domain/Approval.java
> +@NoArgsConstructor
접근지정자를 이용해보세요. public, private, protected, default 중에 머가 좋을까요?

2020-05-25 18:55 UTC, korea8378 requested changes

2020-05-25 18:55 UTC, korea8378 commented on src/main/java/mashup/backend/hoowook_hoowwok/document/domain/approval/Approval.java
> +
결재 승인/거절시 코멘트를 달수 있도록 했던것 같은데 안보이는거 같네요 추가해주시면 좋을것 같습니다.

2020-05-26 04:16 UTC, korea8378 approved these changes

2020-05-26 04:20 UTC, secureWKkim commented
👍🏻

2020-05-26 04:21 UTC, secureWKkim approved these changes

2020-05-26 04:21 UTC, merged